urlRails: "https://www.railstutorial.org/"
urlMichael: "http://www.michaelhartl.com/"
urlBook: "https://www.railstutorial.org/book"
urlScreencasts: "http://screencasts.railstutorial.org/"
urlRubyRails: "http://rubyonrails.org/"
urlContact: "https://www.railstutorial.org/contact"
urlHelp: "https://www.railstutorial.org/help"